### ISSUE TITLE
Implement MailChimp API 3.0

### ISSUE THREAD

**Issue by ruscoe** [thinkshout/mailchimp#178]
- Docs: http://developer.mailchimp.com/documentation/mailchimp/reference/overview/
- Full REST support; GET, POST, PATCH, and DELETE
- HTTP Basic Auth now used with API key
- API now responds with appropriate HTTP response codes. Any codes in the 200 range can be considered successes. Other codes will throw exceptions in the PHP library.
  - We no longer need to parse the response for potential error messages.

**_TODO**_
- [x] Create new library for v3 API
  - https://github.com/thinkshout/mailchimp-api-php
- [x] Implement required API calls in new library
- [x] Update library requirement for new library

lists
- [x] getList
- [x] interestGroupings
- [x] mergeVars
- [x] memberInfo
- [x] memberActivity
- [x] subscribe
- [x] updateMember
- [x] members
- [x] batchSubscribe
- [x] unsubscribe
- [x] segments
- [x] segmentAdd
- [x] webhooks
- [x] webhookAdd
- [x] webhookDel

campaigns
- [x] create
- [x] update
- [x] send
- [x] sendTest
- [x] delete
- [x] getList
- [x] segmentTest (replaced by `MailchimpLists::getSegmentMembers()`)

templates
- [x] getList
- [x] info

reports
- [x] summary

helper
- [x] campaignsForEmail (no longer needed)
- [x] listsForEmail (replaced by `MailchimpLists::getListsForEmail()`)

**Comment by ruscoe** [comment]
**Track API discrepancies here:**
- [x] List webhooks are missing from the API
  - Will be added soon
- [x] Merge fields do not contain default `EMAIL` field
  - Intentional. EMAIL is required on all lists, so is not returned by API.
- [x] Helper functions deprecated. Need custom functions to:
  - Get lists for an email address (was `listsForEmail()`)
  - Get campaigns for an email address (was `campaignsForEmail()`)

**Comment by ruscoe** [comment]
**Test mergefield types**
- [x] text
- [x] dropdown
- [x] radio
- [x] email
