### ISSUE TITLE
Drupal 8 Miscellaneous Task List

### ISSUE THREAD

**Issue by ruscoe** [thinkshout/mailchimp#88]
- [x] If helper functions in a .module file are only used in one form, move them into that form's class
- [x] Remove old admin .inc files once converted to forms / controllers
- [x] Correct any broken function comments
